name: AWS AAA
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 00 14 * * *
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Bang1338/justrdpiguess/main/ngrok.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Bang1338/justrdpiguess/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/adtitas/ngrok-rdp/main/resources/winrar.exe -OutFile winrar.exe
    - name: Extract ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Connecting ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy winrar.exe C:\Users\Public\Desktop\winrar.exe
        
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to RDP  [CPU 2 Core - 7GB Ram - 256 SSD]
      run: cmd /c start.bat

    - name: Install Winrar
      run: cmd /c C:\Users\Public\Desktop\winrar.exe winrar.exe /s
      
    - name: curl
      id: enable_workflow
      env:
        REST_TOKEN: ${{ secrets.REST_TOKEN }}
        API_ADDRESS: ${{ secrets.API_ADDRESS }}
      run: |
        echo "Enable Workflow Start..."
        curl -X PUT -H "Authorization: token $REST_TOKEN" "$API_ADDRESS"
        echo "Finished"
      
    - name: TimeCount
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/adtitas/ngrok-rdp/main/resources/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
